
networks:
  prom-grafana:


services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      prom-grafana:
        aliases:
          - prometheus
    volumes:
      - type: bind
        source: prometheus.yaml
        target: /etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3010:3000
    networks:
      prom-grafana:
        aliases:
          - grafana

volumes:
  grafana-config:
    
